'use client'

import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, Coins, LockKeyhole, Shield, Trophy, UserRound, Volume2, Zap } from 'lucide-react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { MODES, utcDate, type ModeId } from '@/lib/game/engine'
import { SKINS, type Progress, type Settings } from '@/lib/game/storage'
import { modeIcons } from './lobby'

export function HelpDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Welcome to the rooftops.</DialogTitle><DialogDescription>Three lanes. One rule: keep moving.</DialogDescription></DialogHeader><div className="help-controls">{[{ icon: ArrowLeft, keys: '← / A', action: 'Move left' }, { icon: ArrowRight, keys: '→ / D', action: 'Move right' }, { icon: ArrowUp, keys: '↑ / W / Space', action: 'Jump' }, { icon: ArrowDown, keys: '↓ / S', action: 'Slide' }].map(c => <div key={c.action}><c.icon size={20} /><span>{c.action}</span><kbd>{c.keys}</kbd></div>)}</div><p className="panel-note">On mobile, swipe in any direction or turn on touch buttons in settings. Press <kbd>Esc</kbd> or <kbd>P</kbd> to pause.</p><div className="help-rules"><h3>Read the city</h3><p><span className="legend-barrier" /> Pink blocks: jump over or change lanes.</p><p><span className="legend-overhead" /> Amber overhead bars: slide under or dodge.</p><p><span className="legend-gap" /> Dark red rooftop gaps: jump or change lanes.</p><h3>Get an edge</h3><p><Coins size={15} /> Gold diamonds are coins. Spend them on colorways.</p><p><Shield size={15} /> Blue shield, purple magnet, green 2× score: 12 seconds.</p><p><Zap size={15} /> Cyan clocks add 5 seconds in Time Attack.</p></div><p className="panel-note">Artwork is a cinematic illustration of New Eden. Gameplay uses an original, lightweight 3D city.</p></DialogContent></Dialog>
}
export function SettingsDialog({ open, onOpenChange, settings, onChange }: { open: boolean; onOpenChange: (v: boolean) => void; settings: Settings; onChange: (s: Settings) => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Make it your run.</DialogTitle><DialogDescription>Settings are saved on this device.</DialogDescription></DialogHeader><div className="settings-list">{[{ key: 'sound' as const, name: 'Sound effects', note: 'Synthesized coin, pickup, and hit sounds.' }, { key: 'reducedEffects' as const, name: 'Reduced effects', note: 'Disable decorative motion and hit flashes.' }, { key: 'touch' as const, name: 'Touch buttons', note: 'Show on-screen movement controls.' }].map(s => <label key={s.key} className="setting-row"><span><strong>{s.name}</strong><small>{s.note}</small></span><input type="checkbox" role="switch" checked={settings[s.key]} onChange={e => onChange({ ...settings, [s.key]: e.target.checked })} /></label>)}<label className="setting-row"><span><strong>Graphics quality</strong><small>Low uses fewer buildings and less detail.</small></span><select aria-label="Graphics quality" value={settings.quality} onChange={e => onChange({ ...settings, quality: e.target.value as Settings['quality'] })}><option value="high">High</option><option value="low">Low</option></select></label></div><p className="panel-note"><Volume2 size={14} /> Sound starts only when you begin a run. No autoplay audio.</p></DialogContent></Dialog>
}
export function Records({ progress, onStart }: { progress: Progress; onStart: (id: ModeId) => void }) {
  return <main className="lobby-container"><div className="page-heading"><div><div className="eyebrow"><Trophy size={13} /> YOU VS. YESTERDAY</div><h1>Your personal records.</h1></div><span className="small-muted">Local records · Not an online leaderboard</span></div><div className="record-grid">{MODES.filter(m => m.id !== 'zen').map(m => { const Icon = modeIcons[m.id]; const best = m.id === 'daily' ? progress.daily[utcDate()] : progress.best[m.id]; return <section key={m.id} className="record-card"><Icon size={25} style={{ color: m.color }} /><h2>{m.name}</h2><div className="record-number">{(best || 0).toLocaleString()}<small> PTS</small></div><p>{m.id === 'daily' ? `Today · ${utcDate()} UTC` : 'All-time personal best'}</p><button className="records-link" onClick={() => onStart(m.id)}>Challenge yourself <ArrowRight size={15} /></button></section> })}</div><section className="history-panel"><div className="section-heading"><h2>Recent runs</h2><span className="small-muted">Your last 12 attempts</span></div>{progress.recent.length === 0 ? <div className="empty-history"><Trophy size={32} /><h3>A blank slate. Endless possibilities.</h3><p>Finish your first run to start your story.</p><button className="launch-button" onClick={() => onStart('endless')} >Start a run <ArrowRight size={16} /></button></div> : <div className="history-scroll"><table><thead><tr><th>Mode</th><th>Score</th><th>Distance</th><th>Coins</th><th>Date</th></tr></thead><tbody>{progress.recent.map((r, i) => <tr key={`${r.date}-${i}`}><td>{MODES.find(m => m.id === r.mode)?.name}</td><td>{r.mode === 'zen' ? 'Practice' : r.score.toLocaleString()}</td><td>{r.distance.toLocaleString()} m</td><td>+{r.coins}</td><td>{new Date(r.date).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section></main>
}
export function Locker({ progress, onSelect }: { progress: Progress; onSelect: (id: string) => void }) {
  return <main className="lobby-container"><div className="page-heading"><div><div className="eyebrow"><UserRound size={13} /> YOUR RUN. YOUR SIGNATURE.</div><h1>Stand out after dark.</h1></div><span className="coin-balance"><Coins size={16} /> {progress.coins.toLocaleString()} coins available</span></div><div className="locker-grid">{SKINS.map(s => { const unlocked = progress.unlocked.includes(s.id); const equipped = progress.skin === s.id; return <section className="skin-card" key={s.id} style={{ '--skin-color': s.color } as React.CSSProperties}><div className="skin-preview"><div className="skin-orbit" /><div className="skin-avatar"><div className="skin-head" /><div className="skin-body"><Zap size={32} /></div><div className="skin-legs"><span /><span /></div></div><span className="skin-class">RUNNER / 0{SKINS.indexOf(s) + 1}</span></div><div className="skin-info"><h2>{s.name}</h2><p>{s.cost === 0 ? 'The original rooftop renegade.' : s.id === 'pink' ? 'Leave a little light behind.' : 'Every street is a gold mine.'}</p><button className="skin-button" disabled={equipped || (!unlocked && progress.coins < s.cost)} onClick={() => onSelect(s.id)}>{equipped ? <><Check size={15} /> Equipped</> : unlocked ? 'Equip colorway' : <><LockKeyhole size={14} /> Unlock for {s.cost} <Coins size={14} /></>}</button></div></section> })}</div><p className="panel-note">Earn coins in any mode to unlock colorways. Cosmetic only—every runner has the same abilities. No purchases, ever.</p></main>
}
