import test from 'node:test'
import assert from 'node:assert/strict'
import { RunnerEngine, type EntityKind } from './engine'
import { defaultProgress, parseProgress, recordRun, selectSkin } from './storage'

function running(mode: ConstructorParameters<typeof RunnerEngine>[0] = 'endless') { const e = new RunnerEngine(mode, '2026-09-12', 31); e.phase = 'running'; e.entities = []; e.nextAt = 9999; return e }
function hazard(e: RunnerEngine, kind: EntityKind, lane = 0) { e.entities = [{ id: 1, at: e.distance + .3, lane, kind, hit: false }] }
function advance(e: RunnerEngine, seconds: number) { for (let i = 0; i < seconds * 60; i++) e.step(1 / 60) }

test('daily routes are repeatable on a UTC date, and change next day', () => { const a = new RunnerEngine('daily', '2026-09-12', 1); const b = new RunnerEngine('daily', '2026-09-12', 88); const c = new RunnerEngine('daily', '2026-09-13'); assert.deepEqual(a.entities, b.entities); assert.notDeepEqual(a.entities, c.entities) })
test('every generated obstacle row leaves at least one safe lane', () => { for (let i = 0; i < 100; i++) { const e = new RunnerEngine('hardcore', '2026-09-12', i); const rows = new Map<number, Set<number>>(); for (const item of e.entities) if (['barrier', 'gap', 'overhead'].includes(item.kind)) { const set = rows.get(item.at) || new Set(); set.add(item.lane); rows.set(item.at, set) }; for (const lanes of rows.values()) assert.ok(lanes.size <= 2) } })
test('barriers and gaps eliminate a grounded runner', () => { for (const kind of ['barrier', 'gap'] as const) { const e = running(); hazard(e, kind); e.step(.02); assert.equal(e.phase, 'results') } })
test('jump clears barriers and gaps', () => { for (const kind of ['barrier', 'gap'] as const) { const e = running(); e.jump = .45; hazard(e, kind); e.step(.02); assert.equal(e.phase, 'running') } })
test('slide clears overhead obstacles but not barriers', () => { const e = running(); e.action('slide'); hazard(e, 'overhead'); e.step(.02); assert.equal(e.phase, 'running'); hazard(e, 'barrier'); e.step(.02); assert.equal(e.phase, 'results') })
test('lane movement is bounded and avoids other lanes', () => { const e = running(); e.action('left'); e.action('left'); assert.equal(e.lane, -1); advance(e, .4); assert.ok(e.x < -2.3); hazard(e, 'barrier', 1); e.step(.02); assert.equal(e.phase, 'running') })
test('shield absorbs one hit and grants recovery', () => { const e = running(); e.shield = 10; hazard(e, 'barrier'); e.step(.02); assert.equal(e.phase, 'running'); assert.equal(e.shield, 0); assert.equal(e.invincible, 2) })
test('pause freezes distance, timer, powers, and countdown', () => { const e = running('time'); e.shield = 4; e.pause(); const before = e.snapshot(); advance(e, 5); assert.deepEqual(e.snapshot(), before); e.resume(); e.step(.02); assert.ok(e.time < before.time); const c = new RunnerEngine('daily'); c.pause(); advance(c, 1); assert.equal(c.countdown, 3) })
test('time attack picks up time, caps it, penalizes hits, and ends at zero', () => { const e = running('time'); e.time = 89; hazard(e, 'time'); e.step(.02); assert.equal(e.time, 90); hazard(e, 'barrier'); e.step(.02); assert.ok(e.time < 82); assert.equal(e.phase, 'running'); e.time = .01; e.step(.02); assert.equal(e.phase, 'results') })
test('hardcore has triple distance scoring and no shield generation', () => { const e = running('hardcore'); e.step(.02); assert.ok(e.score >= e.distance * 2.99); for (let i = 0; i < 30; i++) assert.ok(!new RunnerEngine('hardcore', '2026-09-12', i).entities.some(item => item.kind === 'shield')) })
test('daily completes after 90 seconds and zen never eliminates', () => { const e = running('daily'); advance(e, 91); assert.equal(e.phase, 'results'); const zen = running('zen'); hazard(zen, 'gap'); zen.step(.02); assert.equal(zen.phase, 'running'); assert.equal(zen.score, 0) })
test('magnet collects across lanes and temporary effects expire', () => { const e = running(); e.magnet = 2; hazard(e, 'coin', 1); e.step(.02); assert.equal(e.coins, 1); advance(e, 3); assert.equal(e.magnet, 0) })
test('storage recovers from malformed, wrong-version and invalid values', () => { assert.deepEqual(parseProgress('{'), defaultProgress()); assert.deepEqual(parseProgress('{"version":7}'), defaultProgress()); const p = parseProgress('{"version":1,"coins":-9,"best":{"endless":"bad"},"skin":"gold"}'); assert.equal(p.coins, 0); assert.equal(p.best.endless, 0); assert.equal(p.skin, 'cyan') })
test('run results update records and validate cosmetic purchases', () => { const e = running('daily'); e.score = 1000; e.coins = 140; e.finish(); let p = recordRun(defaultProgress(), e); assert.equal(p.daily['2026-09-12'], 1000); assert.equal(p.recent.length, 1); p = selectSkin(p, 'pink'); assert.equal(p.coins, 40); assert.equal(p.skin, 'pink'); assert.equal(selectSkin(p, 'gold').skin, 'pink'); assert.equal(parseProgress(JSON.stringify(p)).skin, 'pink') })
test('fresh retries reset all transient state', () => { const e = running(); e.action('jump'); e.shield = 3; e.finish(); const retry = new RunnerEngine('endless'); assert.equal(retry.phase, 'countdown'); assert.equal(retry.jump, 0); assert.equal(retry.shield, 0); assert.equal(retry.distance, 0); assert.equal(retry.coins, 0) })
